### PR TITLE
Decredify hard fork voting and consensus page

### PR DESCRIPTION
**Pull request by s-ben**
In this PR, I re-write the text for the 'Hard Fork Voting and Consensus Rule Changes' page to Decredify it. In the process, I realized this should be the same as Bitcoin at the PoW level, so not making any material changes. However, wanted to submit this for review before going any further just to make sure I'm not wrong about how this works. Text from the BTC dev docs is left at the bottom of the page for reference. Assuming PoW chain splits work the same in Decred as Bitcoin, I suppose we next want to incorporate the PoS voting mechanism, fork resistance, etc.?

### CODE REVIEW

**Comment by s-ben** [comment]
Makes sense. Have opened an Issue: https://github.com/jholdstock/dcrdevdocs/issues/16

Not sure where I got the `C` in opCode...thought that was from the Bitcoin docs, but must've picked it up elsewhere.

**Comment by jholdstock** [comment]
Can you update this PR to remove the page, its related images and its menu entry?

**Comment by s-ben** [comment]
Was going to do that, but there's nothing else in this PR. In the new Issue I just link to the branch that has my rewrite of the BTC content, in case we want it later. So there's really no need for this PR I think. Just close it?

**Comment by jholdstock** [comment]
We need to remove `hard-fork-voting-and-consensus-rule-changes.md` and the menu entry from `mkdocs.yml`

**Pull request closed without merging**
